from PySide6.QtWidgets import QMessageBox

from infra.entities.itensPedido import PedidoFornecedor

from infra.repository.produto_repository import ProdutoRepository
from infra.repository.pedidoFornecedor_repository import PedidoFornecedorRepository
from infra.service.main_window_service import MainWindowService
